version: '0.27.{build}'
image: 
- Visual Studio 2017
- Ubuntu
stack: node 9
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:  
       secure: nc3dHpY/e540t89127H4VJmUyIguGDiHKoASVRtcDU+LBiBtY9UvicRdZUgcGuYf
  op_build_user: "Geo Perez"
  op_build_user_email: "geovanni.perez@gmail.com"
  access_token:
       secure: HzWdswNyfQbQ0vLk9IQyO+Ei9mxoPYp9rvv6HPhtC9J/Fm7EHRzyV953pbPRXI9I
before_build:
- ps: Write-Host "TItle $env:APPVEYOR_PULL_REQUEST_TITLE Windows $isWindows"
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $isWindows)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y --no-progress
        }
- ps: |
        if($isWindows)
        {
            Install-Product node 8
        }
- npm i npm@latest -g
- npm install -q
- ps: $LDAP = Start-Process node ldap.js -PassThru
- ps: $SMTP = Start-Process node mail.js -PassThru
- ps: $WEB = Start-Process node web.js -PassThru
- ps: $TCP = Start-Process node tcp.js -PassThru
- ps: $NTP = Start-Process node ntp.js -PassThru
- dotnet restore -v Minimal
- cmd: mkdir tools
- cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- cmd: nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
build_script:
- cmd: msbuild /p:Configuration=Release /verbosity:quiet
- sh: |
        cd src/Unosquare.Swan
        msbuild /verbosity:quiet /p:Configuration=Release;TargetFrameworks="netstandard2.0;netstandard1.3;net452"
        cd ..
        cd ..
test_script:
- dotnet test test/Unosquare.Swan.Test/Unosquare.Swan.Test.csproj -c Release -f netcoreapp2.1
- cmd: tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"%ProgramFiles%\dotnet\dotnet.exe" -targetargs:"test test/Unosquare.Swan.Test/Unosquare.Swan.Test.csproj -c Release -f net46" -output:coverage.xml -filter:"+[Unosquare.Swan*]* -[Unosquare.Swan.Test*]*" -register:userdotnet
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $isWindows)
        {
            tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%
        }
after_build:
- ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $isWindows)
        {
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            git config --global core.autocrlf false 
            git config --global user.email $env:op_build_user_email
            git config --global user.name $env:op_build_user
            git clone https://github.com/unosquare/swan.git -b gh-pages origin_site -q
            git clone -b documentation https://github.com/unosquare/best-practices.git -q
            git clone https://github.com/unosquare/swan.wiki.git -q wiki
            docfx docfx.json --logLevel Error
            Copy-Item origin_site/.git _site -recurse
            CD _site
            Copy-Item README.html index.html -force
            git add -A 2>&1
            git commit -m "Documentation update" -q
            git push origin gh-pages -q
            CD ..
        }
on_finish:
- ps: Stop-Process -Id $LDAP.Id
- ps: Stop-Process -Id $SMTP.Id
- ps: Stop-Process -Id $WEB.Id
- ps: Stop-Process -Id $TCP.Id
- ps: Stop-Process -Id $NTP.Id
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
