on: 
  workflow_call:
    secrets:
      github-token:
        description: 'The GitHub PAT token to perform checkout and publish.'
        required: true
    inputs:
      project-name:
        description: 'The name of the swan project to build. Must match the directory name.'
        required: true
        type: string
      base-path:
        description: 'The working directory base path with a trailing fwd-slash'     
        required: true
        default: '/home/runner/work/swan/swan/src/'
        type: string
      prerelease-versions-kept:
        description: 'The number of pre-release versions kept in the GitHup registry.'
        required: true
        type: number
        default: 10
      version-bump-level:
        description: 'The version component to bump after publishing.'
        required: true
        default: ${{ contains(github.event.head_commit.message, '[PATCH]') && 'patch' || contains(github.event.head_commit.message, '[MINOR]') && 'minor' || contains(github.event.head_commit.message, '[MAJOR]') && 'major' || 'prerelease' }}
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ Bump version
      uses: unosquare/bump-nuget-version@master 
      with:
        level: ${{ inputs.version-bump-level }}
        csproj: '${{ inputs.base-path }}${{ inputs.project-name }}/${{ inputs.project-name }}.csproj'
    - name: ğŸ— Build and pack nuget
      run: |
        dotnet pack '${{ inputs.base-path }}${{ inputs.project-name }}/${{ inputs.project-name }}.csproj' --configuration Release 
    - name: ğŸ± Publish nuget
      uses: unosquare/publish-nuget-package@master
      with:
        access-token: ${{ secrets.github-token }}
        path: '${{ inputs.base-path }}${{ inputs.project-name }}/bin/Release'
    - name: ğŸ“Œ Commit
      uses: EndBug/add-and-commit@v7
      with:
        message: '[skip ci]'
    - name: ğŸŒ¿ Clean up stale packages
      uses: actions/delete-package-versions@v2
      with: 
        package-name: ${{ inputs.project-name }}
        min-versions-to-keep: ${{ inputs.prerelease-versions-kept }}
        delete-only-pre-release-versions: 'true'
  
