# This GitHub Action bumps up the <Version /> tag in the csproj file depending on the commit's comment:
#   SemVer format is: MAJOR.MINOR.PATCH-PRERELEASE
#   If the commit's comment contains the string [MAJOR], [MINOR] or [PATCH] it bumps it accordingly.
#   If no matching bump commment is found, the PRERELEASE component gets bumped.
# Finally, it builds the project in .net 5 and .net 6, and publishes it to the local GitHub package registry.
# by @geoperez and @mariodivece
name: Pack and Publish
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: unosquare/swan/.github/actions/ci-swan@master
      with:
        project-name: 'Swan.Core'
        github-token: ${{ secrets.MAD_PACKAGE_MGMNT }}
